#
#   campaigns
#

[campaigns]

#
#   ALIEN STANDARD
#

[campaigns.alien_research_early]
name = 'Resefaction H'
score = 0
faction = 'aliens'
tech_startrt = [ ]
tech_end = [ ]
regions = { 'north_america' = 10, 'south_america' = 5, 'europe' = 12 }

[[campaigns.alien_research_early.missions]]
ufo = 'alien_small_scout'
count = 1
timer = 9
[[campaigns.alien_research_early.missions]]
ufo = 'alien_medium_scout'
count = 1
timer = 7



[campaigns.alien_research]
name = 'Resefaction H'
score = 0
faction = 'aliens'
tech_startrt = [ ]
tech_end = [ ]
regions = { 'north_america' = 10, 'south_america' = 5, 'europe' = 12 }

[[campaigns.alien_research.missions]]
ufo = 'alien_small_scout'
count = 1
timer = 9
[[campaigns.alien_research.missions]]
ufo = 'alien_medium_scout'
count = 1
timer = 7
[[campaigns.alien_research.missions]]
ufo = 'alien_excavator'
count = 1
timer = 2
[[campaigns.alien_research.missions]]
ufo = 'alien_large_scout'
count = 2
timer = 9
[[campaigns.alien_research.missions]]
ufo = 'alien_lab_ship'
count = 1
timer = 9
deployments =  { 'alien_lab_ship_sectoid' = 5, 'alien_lab_ship_floater' = 3, 'alien_lab_ship_muton' = 3 }

#
#   MAN IN BLACK
#

[campaigns.mib_supply]
name = "MIB Supply"
score = 20
objective = 5
faction = 'mib'
tech_startrt = [ ]
tech_end = [ ]
regions = { 'europe' = 12 }

[[campaigns.mib_supply.missions]]
ufo = 'mib_engineering_ship'
count = 1
timer = 6


[campaigns.mib_outpost]
name = "MIB Outpost"
score = 20
objective = 2
faction = 'mib'
tech_startrt = [ ]
tech_end = [ ]
regions = { 'europe' = 12 }

[[campaigns.mib_outpost.missions]]
ufo = 'mib_engineering_ship'
count = 1
timer = 2


#
#   EXALT
#

[campaigns.exalt_supply]
name = "EXALT Supply"
score = 20
objective = 5
faction = 'exalt'
tech_startrt = [ ]
tech_end = [ ]
regions = { 'north_america' = 12, 'south_america' = 9 }

[[campaigns.exalt_supply.missions]]
ufo = 'exalt_suppy_ship'
count = 1
timer = 6

#
#   ZOMBIE
#

[campaigns.zombie_attack]
name = "Zombie Attack"
score = 20
faction = 'zombie'
tech_startrt = [ ]
tech_end = [ ]
regions = { 'north_america' = 12, 'south_america' = 9 }

[[campaigns.zombie_attack.missions]]
site = 'zombie_attack'
count = 1
timer = 20

[[campaigns.zombie_attack.missions]]
site = 'zombie_attack'
count = 1
timer = 20

[[campaigns.zombie_attack.missions]]
site = 'zombie_attack'
count = 1
timer = 20

[[campaigns.zombie_attack.missions]]
site = 'zombie_attack'
count = 1
timer = 20