#
#   factions
#

[factions]

[factions.xcom]
name = "XCOM"
pedia = 'faction_xcom'
description = "The Extraterrestrial Combat Unit, XCOM is a secret organization dedicated to defending Earth from alien threats."
id = 0
tech_start = [ ]
tech_end = [ ]


[factions.aliens]
name = "Aliens Mars"
pedia = 'faction_aliens'
description = "Aliens on Mars, a secret organization dedicated to defending Mars from human threats."
id = 1
tech_start = [ ]
tech_end = [ ]


[factions.syndicate]
name = "The Syndicate"
pedia = 'faction_syndicate'
description = "A powerful and secretive organization that operates in the shadows, manipulating events to their advantage."
id = 2
tech_start = [ ]
tech_end = [ ]


[factions.council]
name = "The Council"
pedia = 'faction_council'
description = "A powerful and secretive organization that operates in the shadows, manipulating events to their advantage."
id = 3
tech_start = [ ]
tech_end = [ ]


[factions.mib]
name ="Man in Black"
pedia = 'faction_mib'
description = "A secret organization dedicated to protecting humanity from extraterrestrial threats."
id = 4
tech_start = [ ]
tech_end = [ ]


[factions.exalt]
name = "EXALT"
pedia = 'faction_exalt'
description = "A secret organization dedicated to advancing human interests, often at the expense of others."
id = 5
tech_start = [ ]
tech_end = [ ]


[factions.bos]
name = 'The Brotherhood'
pedia = 'faction_bos'
description = 'A secret organization dedicated to advancing human interests, often at the expense of others.'
id = 6
tech_start = [ ]
tech_end = [ ]
