#
#   REGIONS
#
#   each tile MUST be assigned to region
#   is either land or water
#   region has a weight for mission selection

[regions]

[regions.europe]
name = "Europe"
is_land = true
description = "A continent known for its rich history and diverse cultures."
id = 1
color = '#FF00FF'
mission_weight = 18
base_cost = 800

service_provided = []
service_forbidden = []

[regions.north_africa]
name = "North Africa"
is_land = true
description = "A continent known for its rich history and diverse cultures."
id = 1
mission_weight = 12
base_cost = 600


[regions.south_africa]

[regions.north_america]

[regions.central_america]

[regions.south_america]

[regions.middle_east]

[regions.russia]

[regions.central_asia]

[regions.siberia]

[regions.china]

[regions.far_east]

[regions.australia]

[regions.artctic]

[regions.antarctic]


# seas

[regions.mediterean]

[regions.north_atlantic]

[regions.south_antantic]













