
# base
facilities = 1

# economy
manufacturing = 1
purchasing = 1
research = 1

# battle
deployments = 1
effects = 1
map_blocks = 1
map_scripts = 1
objectives = 1
terrains = 1
tiles = 1
tilesets = 1

# crafts
crafts = 1
ufo_script = 1
ufos = 1

# globe
biomes = 1
cities = 1
countries = 1
regions = 1
worlds = 1

# items
craft_items = 1
item_modes = 1
unit_armours = 1
unit_items = 1

# pedia
pedia = 1

# sites
sites = 1

# skills
auras = 1
careers = 1
classes = 1
medals = 1
promotions = 1
transformations = 1
wounds = 1

# story
calendar = 1
campaigns = 1
events = 1
factions = 1

# units
races = 1
units = 1

# vars
item_types = 1
start_base = 1
battlemap_sizes = 1
terrain_resistance = 1
armour_resistance = 1
salaries = 1