#
#   CLASSES FOR SOLDIERS
#
#   TYPE
#       0 default is for XCOM to use when soldier is promoted
#       1 is for enemy only
#       2 is for random career path when soldier is hired for first time
#       3 is for soldier transformatoin during gameplay
#       4 is for special awards aka medals
#       5 is for pernament wounds from battle / random events
#       6 is for temporary effects on battle like auras

# STANDARD XCOM PROMOTIONS

[classes]


# TRANSFORMATIONS


[classes.transform_bio_enhanced]
name = "Bio - Transformation"
icon = 'bio_transformation.png'
races = [ "human", 'hybrid' ]
type = 3
description = "Enhanced by bio technology."
stats = { mobility = 1, health = 2, energy = 2, sanity = -1 }
recovery_time = 4
transfer_time = 0
cost = 30
tech_needed = []
service_needed = []


