#
#   CLASSES FOR SOLDIERS
#
#   TYPE
#       0 default is for XCOM to use when soldier is promoted
#       1 is for enemy only
#       2 is for random career path when soldier is hired for first time
#       3 is for soldier transformatoin during gameplay
#       4 is for special awards aka medals
#       5 is for pernament wounds from battle / random events
#       6 is for temporary effects on battle like auras

# STANDARD XCOM PROMOTIONS

[classes]



# WOUNDS ?

[classes.broken_arm]
name = "Medal for nigh operations"
icon = 'injury_broken.png'
races = [ "human", 'hybrid' ]
type = 5
description = "Medal for nigh operations"
stats = { aim = -3, reaction = -3 }
recovery_time = 30

