#
#   SKILLS FOR UNITS
#
#   TYPE
#       3 is for soldier transformatoin during gameplay
#

[transformations]


# TRANSFORMATIONS


[transformations.transform_bio_enhanced]
name = "Bio - Transformation"
icon = 'bio_transformation.png'
races = [ "human", 'hybrid' ]
type = 3
description = "Enhanced by bio technology."
stats = { speed = 1, health = 2, energy = 2, sanity = -1 }
recovery_time = 4
transfer_time = 0
cost = 30
tech_needed = []
service_needed = []


