#
#   SKILLS FOR UNITS
#
#   TYPE
#       5 is for pernament wounds from battle / random events
#

[wounds]

#
# WOUNDS FOR SOLDIERS
#

[wounds.broken_arm]
name = "Medal for nigh operations"
icon = 'injury_broken.png'
races = [ "human", 'hybrid' ]
type = 5
description = "Medal for nigh operations"
stats = { aim = -3, reaction = -3 }
recovery_time = 30

#
#   WOUNDS FOR TANKS
#

[wounds.broken_engine]
name = "Medal for nigh operations"
icon = 'injury_broken.png'
races = [ "tank" ]
type = 5
description = "Medal for nigh operations"
stats = { aim = -3, reaction = -3 }
recovery_time = 30

