# Purchase System Configuration
# Defines what items, units, and crafts can be purchased

[purchasing.laser_rifle]
name = "Laser Rifle"
category = "weapon"
cost = 50000
delivery_time = 3
monthly_limit = 10
black_market = false
required_technologies = ["laser_weapons"]
required_services = ["workshop"]
required_items = {}

# Delivery contents specify what actually gets delivered
[purchasing.laser_rifle.delivery_contents]
items = { "laser_rifle" = 1 }
units = {}
crafts = {}

[purchasing.interceptor_craft]
name = "Interceptor"
category = "craft"
cost = 500000
delivery_time = 14
monthly_limit = 2
black_market = false
required_technologies = ["advanced_aircraft"]
required_services = ["hangar"]
required_items = { "elerium_115" = 5, "alien_alloys" = 10 }

[purchasing.interceptor_craft.delivery_contents]
items = {}
units = {}
crafts = { "interceptor" = 1 }

[purchasing.rookie_soldier]
name = "Rookie Soldier"
category = "unit"
cost = 15000
delivery_time = 7
monthly_limit = 20
black_market = false
required_technologies = []
required_services = ["barracks"]
required_items = {}

[purchasing.rookie_soldier.delivery_contents]
items = { "combat_armor" = 1, "rifle" = 1 }
units = { "rookie" = 1 }
crafts = {}

[purchasing.medical_supplies]
name = "Medical Supplies"
category = "item"
cost = 2000
delivery_time = 1
monthly_limit = 50
black_market = false
required_technologies = []
required_services = []
required_items = {}

[purchasing.medical_supplies.delivery_contents]
items = { "medikit" = 3, "stimpack" = 5 }
units = {}
crafts = {}

[purchasing.alien_tech_sample]
name = "Alien Technology Sample"
category = "item"
cost = 100000
delivery_time = 5
monthly_limit = 1
black_market = true
required_technologies = ["alien_research"]
required_services = ["laboratory"]
required_items = {}

[purchasing.alien_tech_sample.delivery_contents]
items = { "alien_device" = 1, "elerium_sample" = 1 }
units = {}
crafts = {}

# Black Market Configuration
[black_market]
reputation_threshold = 10  # Minimum reputation to access
reputation_decay = 0.1     # Daily reputation loss
price_variance = 0.3       # ±30% price variation
reliability_bonus = 0.05   # Bonus per reputation point

[black_market.suppliers.shadow_broker]
name = "Shadow Broker"
discover_requirements = ["black_market_contacts"]
base_reliability = 0.8
stock_refresh_days = 7
available_items = [
    "plasma_rifle",
    "alien_alloys", 
    "psi_amp",
    "mind_probe"
]

[black_market.suppliers.arms_dealer]
name = "Underground Arms Dealer"
discover_requirements = []  # Always available
base_reliability = 0.9
stock_refresh_days = 3
available_items = [
    "heavy_cannon",
    "auto_cannon", 
    "rocket_launcher",
    "proximity_grenade"
]

[black_market.suppliers.alien_contact]
name = "Alien Defector"
discover_requirements = ["alien_interrogation", "psi_research"]
base_reliability = 0.6
stock_refresh_days = 14
available_items = [
    "sectoid_corpse",
    "floater_corpse",
    "alien_entertainment",
    "elerium_115"
]
