#
#   CRAFTS
#
#       X com crafts on world map
#

[crafts]

[crafts.craft_car]
name = "Car"
description = "A basic vehicle for transportation, the car is fast and agile, but lacks firepower."
pedia_image = "pedia_craft_car"

sell_cost = 20
upkeep_cost = 2
score_lost = 10

map_block = 'map_car'
can_land = true
pilots = 1

shield = 0
shield_regen = 0
health = 20
range = 120
speed = 6

hit_bonus = 0
avoid_bonus = 0
power_bonus = 0

fuel = 'item_fuel'
fuel_capacity = 100
fuel_consumption = 0.1

rate_fuel = 1
rate_rearm = 1
rate_repair = 1

items = 0
item_space = 0

unit_space = 2
tank_space = 0

radar_range = 1
radar_power = 5
cover = 10

[crafts.craft_van]
name = "Van"
description = "A basic vehicle for transportation, the car is fast and agile, but lacks firepower."
pedia_image = "pedia_craft_van"

sell_cost = 30
upkeep_cost = 3
score_lost = 5

map_block = 'map_van'

range = 120
speed = 4
fuel = 'item_fuel'
fuel_capacity = 100
fuel_consumption = 0.3
items = 0
pilots = 1
item_space = 0
unit_space = 4
tank_space = 0
health = 30
radar_range = 1
radar_power = 5

[crafts.craft_interceptor]
name = "Interceptor"
description = "A basic vehicle for transportation, the car is fast and agile, but lacks firepower."
pedia_image = "pedia_craft_interceptor"
sell_cost = 250

upkeep_cost = 250
map_block = 'map_interceptor'

range = 16
speed = 10
fuel = 'item_fuel'
fuel_capacity = 100
fuel_consumption = 2
items = 2
item_space = 4
unit_space = 2
pilots = 1
tank_space = 0
health = 200
radar_range = 4
radar_power = 20

