#
#    ITEM MODES
#

[item_modes]

# SNAP is default

[item_modes.snap]
name = "Snap"
key = ""
ap_cost_modifier = 1.0
range_modifier = 1.0
accuracy_modifier = 1.0
shots = 1
damage_modifier = 1.0

# AIM is for sniper shot, better accuracy, but slower

[item_modes.aim]
name = "Aimed"
key = "Control"
ap_cost_modifier = 1.75
range_modifier = 1.0
accuracy_modifier = 1.50
shots = 1
damage_modifier = 1.0

# STUN is focus on overwheling the target, not killing it

[item_modes.stun]
name = "Stun"
key = "Alt"
ap_cost_modifier = 1.0
range_modifier = 1.0
accuracy_modifier = 1.0
shots = 1
damage_modifier = 1.00

# CRITICAL is focus on critical hit, higher damage but lower accuracy

[item_modes.critical]
name = "Critical"
key = "Alt"
ap_cost_modifier = 1.50
range_modifier = 1.0
accuracy_modifier = 0.75
shots = 1
damage_modifier = 1.50

# BURST is for automatic weapons, a lot of shots, but lower accuracy

[item_modes.burst]
name = "Burst"
key = "Shift"
ap_cost_modifier = 1.25
range_modifier = 1.0
accuracy_modifier = 0.50
shots = 3
damage_modifier = 1.0

# AUTO is for full automatic weapons, it fires until end of ammo, but lower accuracy

[item_modes.auto]
name = "Automatic"
key = "Shift"
ap_cost_modifier = 2.0
range_modifier = 1.0
accuracy_modifier = 0.25
shots = 10
damage_modifier = 1.0

# FAST is for fast weapons, cheaper less accurate shot

[item_modes.fast]
name = 'Fast'
key = "Alt"  # Changed from "Alt?" to "Alt" for valid TOML
ap_cost_modifier = 0.75
range_modifier = 1.0
accuracy_modifier = 0.75
shots = 1
damage_modifier = 1.0

# FAR is to fire in parabol arc, higher range but lower accuracy and damage

[item_modes.far]
name = "Long range"
key = "Alt"  # Changed from "Alt?" to "Alt" for valid TOML
ap_cost_modifier = 1.25
range_modifier = 1.5
accuracy_modifier = 0.75
shots = 1
damage_modifier = 0.75