#
#   TERRAINS -> set of map blocks
#
#
#   map blocks group
#       0 - default
#       1 - landing zone for xcom / ufo
#       2 - road A
#       3 - road B
#       4 - road AB

[terrains]


# --------------------------------------------------------- FARMLANDS


[terrains.farmland]
name = "Farmland"
description = "A fertile area of land used for agriculture, farmland is home to a variety of crops and livestock."
tileset = 'farmland'
script = "farmland"
maps_folder = 'culta'
units_civilian = [ "farmer_01", "farmer_02", "farmer_03" ]

[[terrains.farmland.map_blocks]]
map = "culta01"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta02"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta03"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta04"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta05"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta06"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta07"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta08"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta09"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta10"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta11"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta12"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta13"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta1"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta15"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta16"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta16B"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta17"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta17B"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta18"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta30"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta31"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta32"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta33"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "culta34"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "cultaact00"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "cultaact01"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "cultaact02"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "cultaact02B"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "cultabig01"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "cultabig02"
size = 2
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "cultabig03"
size = 2
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "cultabig04"
size = 2
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "cultafarm00"
size = 1
group = 0
chance = 5

[[terrains.farmland.map_blocks]]
map = "cultafarm17"
size = 1
group = 0
chance = 5

# --------------------------------------------------------- FARMLAND WARM


[terrains.farmland_warm]
name = "Farmland warm climate"
description = "Desc"
tileset = 'farmland'
maps_folder = 'culta'
script = "farmland_warm"
units_civilian = [ "male_01", "male_02", "male_03" ]


# --------------------------------------------------------- FOREST


[terrains.forest]
name = "Forest"
description = "Desc"
tileset = 'forest'
script = "forest"
maps_folder = 'forest'
units_civilian = [ "male_01", "male_02", "male_03" ]

[[terrains.forest.map_blocks]]
map = "forest01"
size = 1
group = 0
chance = 5

[[terrains.forest.map_blocks]]
map = "forest02"
size = 1
group = 0
chance = 5

[[terrains.forest.map_blocks]]
map = "forest03"
size = 1
group = 0
chance = 5


# --------------------------------------------------------- FOREST SNOW


[terrains.forest_snow]
name = "Forest with snow"
description = "Desc"
tileset = 'forest'
script = "forest"
maps_folder = 'forest'
units_civilian = [ "male_01", "male_02", "male_03" ]


[[terrains.forest_snow.map_blocks]]
map = "forest30"
size = 1
group = 0
chance = 5

[[terrains.forest_snow.map_blocks]]
map = "forest31"
size = 1
group = 0
chance = 5

[[terrains.forest_snow.map_blocks]]
map = "forest32"
size = 1
group = 0
chance = 5


# --------------------------------------------------------- DESERT


[terrains.desert]
name = "Sand desert"
description = "Desc"
tileset = 'desert'
script = "desert"
maps_folder = 'desert'
units_civilian = [ "male_01", "male_02", "male_03" ]

[[terrains.desert.map_blocks]]
map = "desert01"
size = 1
group = 0
chance = 5

[[terrains.desert.map_blocks]]
map = "desert05"
size = 1
group = 0
chance = 5

[[terrains.desert.map_blocks]]
map = "desert06"
size = 1
group = 0
chance = 5

[[terrains.desert.map_blocks]]
map = "desert07"
size = 1
group = 0
chance = 5

# --------------------------------------------------------- MARS


[terrains.mars]
name = "Mars planet"
description = "Desc"
tileset = 'mars'
script = "mars"
maps_folder = 'mars'
units_civilian = [ "male_01", "male_02", "male_03" ]


# --------------------------------------------------------- MOUNTAINS


[terrains.mountains]
name = "Empty Mountains"
description = "Desc"
tileset = 'mountains'
script = "mountains"
maps_folder = 'mountains'
units_civilian = [ "male_01", "male_02", "male_03" ]


# --------------------------------------------------------- POLAR


[terrains.polar]
name = "Poland / Tundra"
description = "Desc"
tileset = 'polar'
script = "polar"
maps_folder = 'polar'
units_civilian = [ "male_01", "male_02", "male_03" ]

[[terrains.polar.map_blocks]]
map = "polar01"
size = 1
group = 0
chance = 5

[[terrains.polar.map_blocks]]
map = "polar08"
size = 1
group = 0
chance = 5

[[terrains.polar.map_blocks]]
map = "polar09"
size = 1
group = 0
chance = 5

[[terrains.polar.map_blocks]]
map = "polar14"
size = 1
group = 0
chance = 5

[[terrains.polar.map_blocks]]
map = "polar15"
size = 1
group = 0
chance = 5

[[terrains.polar.map_blocks]]
map = "polar16"
size = 1
group = 0
chance = 5

# --------------------------------------------------------- JUNGLE


[terrains.jungle]
name = "Jungle / Wetlands"
description = "Desc"
tileset = 'jungle'
script = "jungle"
maps_folder = 'jungle'
units_civilian = [ "male_01", "male_02", "male_03" ]


# --------------------------------------------------------- URBAM HOUSING


[terrains.urban_house]
name = "Urbam housing"
description = "Desc"
tileset = 'urban_house'
script = "urban_house"
maps_folder = 'urban'
units_civilian = [ "male_01", "male_02", "male_03" ]


# --------------------------------------------------------- URBAM COMMERCIAL


[terrains.urban_commercial]
name = "Urbam comercial"
description = "Desc"
tileset = 'urban_commercial'
script = "urban_commercial"
maps_folder = 'urban'
units_civilian = [ "male_01", "male_02", "male_03" ]


# --------------------------------------------------------- URBAM INDUSTRIAL


[terrains.urban_industrial]
name = "Urbam industrial"
description = "Desc"
tileset = 'urban_industrial'
script = "urban_industrial"
maps_folder = 'urban'
units_civilian = [ "male_01", "male_02", "male_03" ]


# --------------------------------------------------------- XCOM BASE


[terrains.xbase]
name = "XCOM Base"
description = "Desc"
tileset = 'xbase'
script = "xbase"
maps_folder = 'xbase'


[[terrains.xbase.map_blocks]]
map = "xbase00"
size = 1
group = 0
chance = 5

[[terrains.xbase.map_blocks]]
map = "xbase01"
size = 1
group = 0
chance = 5

[[terrains.xbase.map_blocks]]
map = "xbase02"
size = 1
group = 0
chance = 5

[[terrains.xbase.map_blocks]]
map = "xbase03"
size = 1
group = 0
chance = 5

[[terrains.xbase.map_blocks]]
map = "xbase04"
size = 1
group = 0
chance = 5

[[terrains.xbase.map_blocks]]
map = "xbase05"
size = 1
group = 0
chance = 5

[[terrains.xbase.map_blocks]]
map = "xbase06"
size = 1
group = 0
chance = 5

[[terrains.xbase.map_blocks]]
map = "xbase07"
size = 1
group = 0
chance = 5

[[terrains.xbase.map_blocks]]
map = "xbase08"
size = 1
group = 0
chance = 5

[[terrains.xbase.map_blocks]]
map = "xbase09"
size = 1
group = 0
chance = 5

[[terrains.xbase.map_blocks]]
map = "xbase10"
size = 1
group = 0
chance = 5

[[terrains.xbase.map_blocks]]
map = "xbase11"
size = 1
group = 0
chance = 5

# --------------------------------------------------------- ALIEN BASE


[terrains.abase]
name = "Alien Base"
description = "Desc"
tileset = 'abase'
script = "abase"
maps_folder = 'abase'

[[terrains.abase.map_blocks]]
map = "abase_01"
size = 1
group = 0
chance = 5

[[terrains.abase.map_blocks]]
map = "abase_02"
size = 1
group = 0
chance = 5

[[terrains.abase.map_blocks]]
map = "abase_03"
size = 1
group = 0
chance = 5
items = { item_golden_x = [4, 5] }
units = { unit_turret = [4, 5] }
show = true


# --------------------------------------------------------- XCOM CRAFT


[terrains.xcraft]
name = "XCOM craft"
description = "Desc"
tileset = 'xcraft'
script = "xcraft"
maps_folder = 'xcraft'
