#
#   CLASSES FOR SOLDIERS
#
#   TYPE
#       0 default is for XCOM to use when soldier is promoted
#       1 is for enemy only
#       2 is for random career path when soldier is hired for first time
#       3 is for soldier transformatoin during gameplay
#       4 is for special awards aka medals
#       5 is for pernament wounds from battle / random events
#       6 is for temporary effects on battle like auras

# STANDARD XCOM PROMOTIONS

[classes]

[classes.sniper]
name = "Sniper"
icon = 'sniper.png'
races = ["human", "orc"]
description = "A master of long-range combat, the sniper excels at picking off enemies from a distance."
technology = [ 'tech_class_sniper' ]
min_level = 0
type = 0
stats = { health = 1, mobility = 1, aim = 2, sanity = 2, will = 1, sight = [ 2, 1 ] }

[classes.scout]
[classes.soldier]
[classes.heavy]
[classes.medic]
[classes.assult]
[classes.ninja]
[classes.leader]
[classes.psychic]
[classes.engineer]
[classes.pilot]


# ALIENS


[classes.alien_soldier]
name = "Soldier (alien)"
icon = 'soldier_alien.png'
races = ["sectoid"]
description = "A grunt."
technology = [ ]
min_level = 0
type = 1
stats = { health = 1, mobility = 1, aim = 2, sanity = 2, will = 1, sight = [ 2, 1 ] }


[classes.alien_navigator]
name = "Navigator (alien)"
icon = 'navigator_alien.png'
races = ["sectoid"]
description = "A grunt."
technology = [ ]
min_level = 0
stats = { health = 1, mobility = 1, aim = 2, sanity = 2, will = 1, sight = [ 2, 1 ] }


[classes.alien_leader]
name = "Leader (alien)"
icon = 'leader_alien.png'
races = ["sectoid"]
description = "A grunt."
technology = [ ]
min_level = 0
stats = { health = 1, mobility = 1, aim = 2, sanity = 2, will = 1, sight = [ 2, 1 ] }


# CAREERS


[classes.career_ranger]
name = "Ranger career"
icon = 'career_ranger.png'
races = [ "human", 'hybrid' ]
type = 2
description = "A ranger in the past."
stats = { reacttions = 1, aim = 1, energy = 1 }


# TRANSFORMATIONS


[classes.transform_bio_enhanced]
name = "Bio - Transformation"
icon = 'bio_transformation.png'
races = [ "human", 'hybrid' ]
type = 3
description = "Enhanced by bio technology."
stats = { mobility = 1, health = 2, energy = 2, sanity = -1 }
recovery_time = 4
transfer_time = 0
cost = 30
tech_needed = []
service_needed = []

# MEDALS


[classes.medal_night_ops]
name = "Medal for nigh operations"
icon = 'nightops.png'
races = [ "human", 'hybrid' ]
type = 4
description = "Medal for nigh operations"
stats = { sight = [ 0, 1 ], cover = [0, 1], sanity = 1 }


# WOUNDS ?

[classes.broken_arm]
name = "Medal for nigh operations"
icon = 'injury_broken.png'
races = [ "human", 'hybrid' ]
type = 5
description = "Medal for nigh operations"
stats = { aim = -3, reaction = -3 }
recovery_time = 30

# AURAS ?

[classes.berzerk]
name = "Battle frenzy"
icon = 'berzerk.png'
races = [ ]
type = 6
description = "Berzerk rage"
stats = { aim = -3, reaction = -3 }
recovery_time = 30
