#
#   ITEM TYPES
#

[item_types]

craft_systems = 2
auxiliary = 4
outfits = 5
throwing = 10
bows = 15
crossbows = 17
melee = 20
pistols = 30
smgs = 40
shotguns = 50
rifles = 60
sniper_rifles = 70
machine_guns = 80
cannons = 90
launchers = 100
heavy_weapons = 110
firearms = 120
mass_driver = 130
explosives = 140
incendiaries = 150
laser = 160
ion = 165
plasma = 170
sonic = 180
electric = 185
emp = 188
chemicals = 190
bioactive = 191
anti_e115 = 192
warp = 193
psi = 198
incapacitate = 200
smoke = 210
clips = 220
grenades = 230
medical = 240
equipment = 250
accessories = 255
junk = 265
shields = 267
other = 270
land = 340
underwater = 350
space = 360
dream = 380
concealable = 400
labor = 405
sports = 410
beach = 415
religious = 420
human_tech = 500
xcom_tech = 510
alien_tech = 520
tleth_tech = 522
shogg_tech = 525
dimension_x_tech = 530
wrecks = 800
corpses = 810
robots = 900
humans = 910
beasts = 920
demons = 920
ghosts = 920
alien_specimens = 930
evidence = 960
hulls = 970
components = 980
built_ins = 998
blanks = 999
