#
#   PEDIA CATEGORY
#

[pedia_category]

crafts = 0
craft_weapons = 1
units = 2
armours = 3
items = 4           # primary secondary items
facilities = 5

races = 6                   # all non alien race
classes = 7                 # classes type 0 only
careers = 8                 # classes type 2 only
transformations = 8         # classes type 3 only
medals = 9                  # classes type 4 only
wounds = 10                 # classes type 5 only
auras = 11                  # classes type 6 only

organizations = 20          # all organizations on all worlds
countries = 21              # all countries on all worlds
regions = 22                # all regions for all worlds
worlds = 23                 # earth, mars, moon
bioms = 26                  # available bioms on world
dossiers = 24               # all dossiers for all worlds
xcom = 25                   # internal xcom communition

alien_ufos = 30             # small scout ufo
alien_races = 31            # autopsy sectoid, tashot
alien_units = 32            # AUTOPSY   sectoid level I
alien_itmes = 33            # plasma weapons, grenades, alien weapons
alien_armours = 34          # sectoid armour, shields,
alien_classes = 35          # medic, navigator, engineer, psionic, type 1 only
alien_missions = 36         # research, base supply
alien_artefacts = 37        # alien alloys, zrbite, power navigation






[pedia]

[pedia.laser_pistol]
type = 4
name = "Laser Pistol"
section = "Weapons"
description = "A basic laser pistol, providing minimal protection."
image = "laser_pistol.png"
required_tech = [ "laser_tech" ]
order = 2500


[pedia.personal_armour]
type = 4
name = "Personal Armour"
section = "Armours"
description = """
A basic armour suit, providing minimal protection.
"""
image = "personal_armour.png"
required_tech = [ "laser_tech" ]
order = 1500