#
#   RESEARCH
#

[research]

[research.laser_weapons]
name = "Laser weapons"
cost = 50
points = 10

[research.psi_amp]
name = "Psi Amp"
cost = 500
points = 20

# must have all to unlock this
tech_needed = [ 'psi_lab' ]

# give one free from list
tech_give = [ 'snakeman_autopsy', 'sectoid_autopsy' ]

# unlock this regardless other requirements
tech_unlock = [ 'cydonia_or_bust' ]

# disable this, so it wont be available in future
tech_disable = [ ]

# services are provided by base facility, so its required
service_needed = [ 'service_name' ]

# after completed spawn event
event_spawn = 'event_name'

# create item after done
item_spawn = { 'psi_amp' : 1 }

# item needed to start resarch, flag if item is removed
item_needed = { 'psi_amp' = true }

# ufo pedia entry when completed
pedia = 'psi_amp'

complete_game = false