#
#   MISSIONS
#
#   OBJECTIVE
#       0 -> scout / score only
#       1 -> infitrlation, impact country
#       2 -> build alien base
#       3 -> mission site / terror
#       4 -> retaliation, find xcom base and attack
#       5 -> supply existing alien base
#       6 -> hunt x-com crafts, protect other ufos
#       7 -> destroy terrain / convert to another type ? biomass etc

#
#   MISSIONS
#

[missions]

#
#   ALIEN STANDARD
#

[missions.alien_research_early]
score = 0
arc = 'aliens'
technology_start = [ ]
technology_end = [ ]
regions = { 'north_america' = 10, 'south_america' = 5, 'europe' = 12 }

[[waves]]
ufo = 'alien_small_scout'
count = 1
timer = 9
[[waves]]
ufo = 'alien_medium_scout'
count = 1
timer = 7



[missions.alien_research]
score = 0
arc = 'aliens'
technology_start = [ ]
technology_end = [ ]
regions = { 'north_america' = 10, 'south_america' = 5, 'europe' = 12 }

[[waves]]
ufo = 'alien_small_scout'
count = 1
timer = 9
[[waves]]
ufo = 'alien_medium_scout'
count = 1
timer = 7
[[waves]]
ufo = 'alien_excavator'
count = 1
timer = 2
[[waves]]
ufo = 'alien_large_scout'
count = 2
timer = 9
[[waves]]
ufo = 'alien_lab_ship'
count = 1
timer = 9
deployments =  { 'alien_lab_ship_sectoid' = 5, 'alien_lab_ship_floater' = 3, 'alien_lab_ship_muton' = 3 }

#
#   MAN IN BLACK
#

[missions.mib_supply]
score = 20
objective = 5
arc = 'mib'
technology_start = [ ]
technology_end = [ ]
regions = { 'europe' = 12 }

[[waves]]
ufo = 'mib_engineering_ship'
count = 1
timer = 6


[missions.mib_outpost]
score = 20
objective = 2
arc = 'mib'
technology_start = [ ]
technology_end = [ ]
regions = { 'europe' = 12 }

[[waves]]
ufo = 'mib_engineering_ship'
count = 1
timer = 2


#
#   EXALT
#

[missions.exalt_supply]
score = 20
objective = 5
arc = 'exalt'
technology_start = [ ]
technology_end = [ ]
regions = { 'north_america' = 12, 'south_america' = 9 }

[[waves]]
ufo = 'exalt_suppy_ship'
count = 1
timer = 6
