#
#   CALENDAR
#
#

[calendar]
start_day = 1997-01-01
end_day = 2004-12-30

#
#   CAMPAIGN
#
#   each month we do create number of random missions of specific arc
#   missions can be blocked by research
#

[campaing]

m00 = { weights = { event = 1 }, qty_min = 1, qty_max = 1 }
m03 = { weights = { event = 1, exalt = 1, dagon = 1}, qty_min = 1, qty_max = 2 }
m06 = { weights = { event = 2, exalt = 1, dagon = 1}, qty_min = 1, qty_max = 2 }
m09 = { weights = { event = 2, exalt = 2, dagon = 1}, qty_min = 1, qty_max = 2 }
m12 = { weights = { event = 2, exalt = 3, dagon = 1}, qty_min = 2, qty_max = 3 }
m15 = { weights = { event = 2, exalt = 3, aliens = 1}, qty_min = 2, qty_max = 3 }
m18 = { weights = { event = 2, exalt = 2, aliens = 2}, qty_min = 2, qty_max = 4 }
m21 = { weights = { event = 2, exalt = 2, aliens = 3}, qty_min = 2, qty_max = 4 }
m24 = { weights = { event = 2, exalt = 1, aliens = 3}, qty_min = 2, qty_max = 4 }
m27 = { weights = { event = 2, exalt = 1, aliens = 3}, qty_min = 3, qty_max = 4 }
m30 = { weights = { event = 2, exalt = 1, aliens = 3}, qty_min = 3, qty_max = 4 }
m33 = { weights = { event = 2, exalt = 1, aliens = 3}, qty_min = 3, qty_max = 4 }
m36 = { weights = { event = 2, exalt = 1, aliens = 3}, qty_min = 3, qty_max = 5 }


#
#   ARCS
#
#   each arc has a specific technology start / end and score modifier
#   from each arc then select random mission that match this arc
#

[arcs]

event = { id = 1, technology_start = [ ], technology_end = [ ] }
zombie = { id = 2, technology_start = [ ],  technology_end = [ 'zombie_solution' ] }
monster = { id = 3,technology_start = [ ],  technology_end = [ ] }

exalt = { id = 4,technology_start = [ ],  technology_end = [ ] }
dagon = { id = 4,technology_start = [ ],  technology_end = [ ] }
red_dawn = { id = 4,technology_start = [ ],  technology_end = [ ] }
lotus = { id = 4, technology_start = [ ],  technology_end = [ ] }

mib = { id = 5,technology_start = [ ],  technology_end = [ ] }
aliens = { id = 6, technology_start = [ ],  technology_end = [ ] }