#
#   MANUFACTURING
#

[manufacturing]

#
#   CRAFT BEAMS
#

[manufacturing.laser_cannon]
category = 'craft_weapon'
technology = [ 'laser_cannon']
time = 300
cost = 180

[manufacturing.plasma_beam]
category = 'craft_weapon'
technology = [ 'plasma_cannon']
time = 500
cost = 220
points = 0
items_needed = { 'elerium_115' = 15 }
items_build = { 'plasma_beam' = 1 }
service_needed = { 'workshop' }
transfer_time = 1

#
#   PLASMA WEAPONS
#

[manufacturing.heavy_plasma]
category = 'weapon'
technology = [ 'heavy_plasma' ]
time = 1000
cost = 120
items_needed = { elerium_115 = 2, alien_alloy = 5 }

#
#   CRAFTS
#

[manufacturing.heavy_plasma]
category = 'craft'
technology = [ 'ultimate_craft' ]
time = 34000
cost = 900
items_needed = { elerium_115 = 2, alien_alloy = 120, ufo_power_source = 2, ufo_navigation = 1 }