#
#   TERRAINS -> set of map blocks
#
#
#   map blocks group
#       0 - default
#       1 - landing zone for xcom / ufo
#       2 - road A
#       3 - road B
#       4 - road AB

[terrains]

# FARMLANDS

[terrains.farmland]
name = "Farmland"
description = "A fertile area of land used for agriculture, farmland is home to a variety of crops and livestock."
tileset = 'farmland'
script = "farmland"
units_civilian = [ "farmer_01", "farmer_02", "farmer_03" ]

[[map_blocks]]
name = "farm_01"
size = 1
group = 0
chance = 5

[[map_blocks]]
name = "farm_02"
size = 1
group = 0
chance = 5

[[map_blocks]]
name = "farm_03"
size = 1
group = 0
chance = 5

# FOREST

[terrains.forest]
name = "Forest"
description = "Desc"
tileset = 'forest'
script = "forest"
units_civilian = [ "male_01", "male_02", "male_03" ]

[[map_blocks]]
name = "forest_01"
size = 1
group = 0
chance = 5

[[map_blocks]]
name = "forest_02"
size = 1
group = 0
chance = 5

[[map_blocks]]
name = "forest_03"
size = 1
group = 0
chance = 5

# FOREST SWAMP

[terrains.forest_swamp]
name = "Forest with swamp"
description = "Desc"
tileset = 'forest'
script = "forest"
units_civilian = [ "male_01", "male_02", "male_03" ]

[[map_blocks]]
name = "forest_01"
size = 1
group = 0
chance = 5

[[map_blocks]]
name = "forest_02"
size = 1
group = 0
chance = 5

[[map_blocks]]
name = "forest_03"
size = 1
group = 0
chance = 5


# ALIEN BASE


[terrains.alien_base]
name = "Alien Base"
description = "Desc"
tileset = 'alien_base'
script = "alien_base"

[[map_blocks]]
name = "abase_01"
size = 1
group = 0
chance = 5

[[map_blocks]]
name = "abase_02"
size = 1
group = 0
chance = 5

[[map_blocks]]
name = "abase_03"
size = 1
group = 0
chance = 5
items = { item_golden_x = [4, 5] }
units = { unit_turret = [4, 5] }
show = true