#
#   ARMOUR RESISTANCE
#

[armour_resistance]

slash = { name = "Slash", description = "Resistance to slash damage.", color = "#FF0000", icon = "slash.png" }
pierce = { name = "Slash", description = "Resistance to slash damage.", color = "#FF0000", icon = "slash.png" }
explosive = { name = "Slash", description = "Resistance to slash damage.", color = "#FF0000", icon = "slash.png" }
laser = {}
plasma = {}
warp = {}
stun = {}
smoke = {}
fire = {}
bio = {}
acid = {}
psionic = {}
emp = {}

#
#   BATTLE MAP SIZES
#

[battlemap_sizes]
micro = [3, 3]
small = [ 4, 4]
medium = [ 5, 5]
large = [ 6, 6]
huge = [ 7, 7]

