#
#   ENVIROMENTAL EFFECT DURING BATTLE
#

[effects]

[effects.insanity_small]
morale_per_turn = -1
sanity_per_mission = -1

[effects.insanity_medium]
morale_per_turn = -2
sanity_per_mission = -2

[effects.insanity_large]
morale_per_turn = -3
sanity_per_mission = -3